language: php

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi

before_script:
  - composer install

script:
  - >
    echo;
    echo "Running unit tests";
    vendor/bin/phpunit --colors tests

  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./vendor/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
